### ISSUE TITLE
Repo Branch No Longer Exists

### ISSUE THREAD

**Issue by myronww** [NextThingCo/Gadget-OS#26]
The Repo branch name specified here:

https://github.com/NextThingCo/Gadget-OS/blob/935eaa0a35a69707f52d4f43e8e279f02cbda793/gadget/configs/chippro_defconfig#L75

as

BR2_TARGET_UBOOT_CUSTOM_REPO_VERSION="ww/2016.01/next"

Does not exist anymore.  This line should probably be something like

BR2_TARGET_UBOOT_CUSTOM_REPO_VERSION="nextthing/2016.01/next"

**Comment by myronww** [comment]
When I modify this line to the below line, my build can continue

BR2_TARGET_UBOOT_CUSTOM_REPO_VERSION="nextthing/2016.01/next"

**Comment by telarium** [comment]
Branch restored
