### ISSUE TITLE
Can't make chippro_defconfig

### ISSUE THREAD

**Issue by ccamrobertson** [NextThingCo/Gadget-OS#5]
Running into a really odd bug here, suspect that it's got to do with my environment. I've initialized the container, but I can't make the chippro_defconfig - instead I get an error indicating that docker isn't found (I've verified the docker image is available from the init command and docker is up and running). Here is what I get when I run `scripts/build-gadget make chippro_defconfig`:

```
Docker enabled :/
BR2_EXTERNAL=/opt/gadget-os-proto/gadget
------------------------------------------------------------
 Running Docker - hit CTRL-C then CTRL-\ to interrupt
------------------------------------------------------------
/bin/sh: 1: docker: not found
Makefile:68: recipe for target 'chippro_defconfig' failed
make: *** [chippro_defconfig] Error 127
```

The odd thing is that I've successfully been able to make configs for gadget-buildroot for a few months; I removed and rebuilt the gadget-build-container image a couple of times (rebuilt from the init container script in Gadget-OS) and still no luck. Conversely, gadget-buildroot has no issues after the rebuild. Here's what it's `scripts/build-gadget make chippro_defconfig` command looks like:

```
make[1]: Entering directory '/opt/buildroot'
mkdir -p /opt/output/build/buildroot-config/lxdialog
PKG_CONFIG_PATH="" make CC="/usr/bin/gcc" HOSTCC="/usr/bin/gcc" \
    obj=/opt/output/build/buildroot-config -C support/kconfig -f Makefile.br conf
make[2]: Entering directory '/opt/buildroot/support/kconfig'
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/opt/output/build/buildroot-config -DCONFIG_=\"\"  -MM *.c > /opt/output/build/buildroot-config/.depend 2>/dev/null || :
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/opt/output/build/buildroot-config -DCONFIG_=\"\"   -c conf.c -o /opt/output/build/buildroot-config/conf.o
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/opt/output/build/buildroot-config -DCONFIG_=\"\"  -I. -c /opt/output/build/buildroot-config/zconf.tab.c -o /opt/output/build/buildroot-config/zconf.tab.o
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/opt/output/build/buildroot-config -DCONFIG_=\"\"   /opt/output/build/buildroot-config/conf.o /opt/output/build/buildroot-config/zconf.tab.o  -o /opt/output/build/buildroot-config/conf
rm /opt/output/build/buildroot-config/zconf.tab.c
make[2]: Leaving directory '/opt/buildroot/support/kconfig'
  GEN     /opt/output/Makefile
#
# configuration written to /opt/output/.config
#
make[1]: Leaving directory '/opt/buildroot
```

I threw in some debug lines to the shell script and it looks like all the docker run arguments are reasonable (i.e. volume names like gadget-build-dlcache-2235).

I also removed the "--rm" option from the docker run command and saw an excited container after the error but didn't get any other useful feedback. It feels like there is a script within the container that wants to call docker but can't find it.

Any sense on whether or not the error is generated from within the docker right after it's being run or if there is some odd environment issue on my side?

**Comment by xtacocorex** [comment]
The container for building between gadget-buildroot and gadget-os are
different.

You're also using the testing branch, I would try running with the unstable
branch.

**Comment by ccamrobertson** [comment]
I suspected that. I removed the old gadget-buildroot image thinking that might be the issue and did a fresh rebuild using the init-container script in Gadget-OS, but sadly no luck.

I switched to unstable early on after I saw it had more activity on it. Error message above is from unstable branch.

**Comment by ccamrobertson** [comment]
Ok, didn't realize that this closely matched what was happening in [https://github.com/NextThingCo/Gadget-OS/issues/3]; I dug into this more closely. 

I'm a novice at Makefiles, but the issue seems to be with the choice of shell; by default make wants to use /bin/sh while I use /bin/zsh. Adding $(...) around the docker run command helps this, but doesn't resolve the issue completely. It would likely be good for a PR, however, I'm still having issues with the `scripts/build-gadget make chippro_defconfig` command. Here's what it throws now:

```
Docker enabled :/
BR2_EXTERNAL=/opt/gadget-os-proto/gadget
------------------------------------------------------------
 Running Docker - hit CTRL-C then CTRL-\ to interrupt
------------------------------------------------------------
make[1]: Entering directory '/opt/buildroot'
make[1]: *** No rule to make target 'chippro_defconfig'.  Stop.
make[1]: Leaving directory '/opt/buildroot'
Makefile:68: recipe for target 'chippro_defconfig' failed
make: *** [chippro_defconfig] Error 2
```

Running `make chippro_defconfig` doesn't work either, yielding the following:

```
BR2_EXTERNAL=/opt/gadget-os-proto/gadget
------------------------------------------------------------
 Running Docker - hit CTRL-C then CTRL-\ to interrupt
------------------------------------------------------------
make: *** /opt/buildroot: No such file or directory.  Stop.
make: *** [chippro_defconfig] Error 2
```

Conversely, `scripts/build-gadget make nconfig` now brings me into the configuration tool as expected (previously it yielded the same docker not found error).

Do I need to do anything with gen-dockerfiles.sh? It looks like the existing Dockerfile within scripts/ doesn't actually add in the gadget directory which would explain to me why it's having trouble (unlike common.Dockerfile). 

I've tried running it but am running into issues with the date command and git complaining about invalid tags; it looks like OS X doesn't like the --iso-8601 option.

**Comment by ccamrobertson** [comment]
There were a few changes and doc updates since my last attempt here; I've resolved my issue by moving back to the `testing` branch and building in a bash shell instead of zsh. This is pretty easy on OS X: `exec bash` from a zsh shell will take you into a bash shell.

The `make` commands now work for me if they're invoked directly (i.e. not prepending with `script/build-gadget`).

I've yet to go back and test under zsh to verify that the issues were definitively tied to the shell as opposed to commits made since my last comment (or invoking `make` directly rather than prepending it with `script/build-gadget`, although this failed previously too). Might be worth a note in the docs in case the shell was the cause.
